# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jushawn/projects/RFID

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jushawn/projects/RFID

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jushawn/projects/RFID/CMakeFiles /home/jushawn/projects/RFID//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jushawn/projects/RFID/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named start_read

# Build rule for target.
start_read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 start_read
.PHONY : start_read

# fast build rule for target.
start_read/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_read.dir/build.make CMakeFiles/start_read.dir/build
.PHONY : start_read/fast

#=============================================================================
# Target rules for targets named IncludeReader

# Build rule for target.
IncludeReader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IncludeReader
.PHONY : IncludeReader

# fast build rule for target.
IncludeReader/fast:
	$(MAKE) $(MAKESILENT) -f Reader/CMakeFiles/IncludeReader.dir/build.make Reader/CMakeFiles/IncludeReader.dir/build
.PHONY : IncludeReader/fast

RFID_communication.o: RFID_communication.cpp.o
.PHONY : RFID_communication.o

# target to build an object file
RFID_communication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_read.dir/build.make CMakeFiles/start_read.dir/RFID_communication.cpp.o
.PHONY : RFID_communication.cpp.o

RFID_communication.i: RFID_communication.cpp.i
.PHONY : RFID_communication.i

# target to preprocess a source file
RFID_communication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_read.dir/build.make CMakeFiles/start_read.dir/RFID_communication.cpp.i
.PHONY : RFID_communication.cpp.i

RFID_communication.s: RFID_communication.cpp.s
.PHONY : RFID_communication.s

# target to generate assembly for a file
RFID_communication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/start_read.dir/build.make CMakeFiles/start_read.dir/RFID_communication.cpp.s
.PHONY : RFID_communication.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IncludeReader"
	@echo "... start_read"
	@echo "... RFID_communication.o"
	@echo "... RFID_communication.i"
	@echo "... RFID_communication.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

